### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by JoelBender** [celery/py-amqp#105]
I have RPC client/server applications [here](https://github.com/JoelBender/amqp-rpc) that work with the 1.4.9 version of the library but I'm struggling to get them working with the current release.  Apart from calling `channel.connect()`, there is now a required parameter to `channel.wait()` and I don't understand what `method` to pass.  The `basic_cancel()` call doesn't "break" the `wait()`.  Help is appreciated, thank you.

**Comment by ask** [comment]
Don't use `channel.wait()`, you should be using `connection.drain_events()` instead.

The channel.wait() was inherited from amqplib where you couldn't wait for events from multiple channels at a time.  I cannot see any reason why you'd want to block waiting for events on a single channel only.   You should use the timeout parameters to connection.drain_events also, catch the socket.timeout error and continue draining in the main loop.

**Comment by JoelBender** [comment]
Thank you.  I haven't updated it to use the timeout parameters yet, just trapping connection failures, but the basics are fine and I'll keep working on it.
