### ISSUE TITLE
Support the 'Auth Failure' RabbitMQ protocol extension

### ISSUE THREAD

**Issue by edmorley** [celery/py-amqp#106]
Whilst the AMQP 0-9-1 spec requires brokers to terminate a connection upon authentication failure, rabbitmq-server has a protocol extension that allows clients who advertise the `authentication_failure_close` capability to instead have the broker send a `connection.close` command to the client with `ACCESS_REFUSED` as the reason.

It would be great to add support for this capability to py-amqp, similar to what was done in rabbitmq-c in alanxz/rabbitmq-c#196, which will help improve the UX seen in celery/kombu#611.

For more details, see:
http://www.rabbitmq.com/auth-notification.html

Many thanks :-)

**Comment by edmorley** [comment]
Support for this was added in 4d52fce.

I don't suppose you could add a mention to the README, under the "Supports RabbitMQ extensions" section? :-)

**Comment by ask** [comment]
Thanks for reminding me!

**Comment by edmorley** [comment]
Thank you!

**Comment by pquentin** [comment]
This breaks existing code which relied on IOError to detect auth errors. Would it make sense to make AccessRefused inherit from IOError?
