### ISSUE TITLE
Cannot import amqp with Python-2.7.5 (TypeError: Struct() argument 1 must be string, not unicode)

### ISSUE THREAD

**Issue by bsergean** [celery/py-amqp#107]
This is the default CentOS 7 version of Python

```
(venv) $ python
Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from amqp import ChannelError, ConnectionError, ResourceError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python2.7/site-packages/amqp/__init__.py", line 48, in <module>
    from .basic_message import Message      # noqa
  File "venv/lib/python2.7/site-packages/amqp/basic_message.py", line 29, in <module>
    from .serialization import GenericContent
  File "venv/lib/python2.7/site-packages/amqp/serialization.py", line 33, in <module>
    from .exceptions import FrameSyntaxError
  File "venv/lib/python2.7/site-packages/amqp/exceptions.py", line 264, in <module>
    _method_name
TypeError: Struct() argument 1 must be string, not unicode
```

It works fine on latest OSX

```
(venv) $ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from amqp import ChannelError, ConnectionError, ResourceError
>>> 
```

**Comment by bsergean** [comment]
This was supposed to be fixed by this

https://github.com/celery/py-amqp/commit/9167f6569e5f48fcb37e6eda8caf9ce81de2dc93

**Comment by bsergean** [comment]
Removing the 'unicode_literals' import, and changing that unicode back to str makes it work with Python 2.7.5.

```
    METHOD_NAME_MAP[unpack(str('>I'), pack(str('>HH'), *_method_id))[0]] = \
```

**Comment by ask** [comment]
Everything is using bytes now, so this should be fixed

**Comment by bsergean** [comment]
Oh cool; is that change available in a new version of celery ?

**Comment by ask** [comment]
@bsergean The current stable version of Celery mandates that amqp < 2.0 should be used, so if you are affected there must be some problem with pip, or similar.  Or maybe you have added a dependency on `amqp` manually?

For Celery 4rc, there's a amqp 2.1.1 no PyPI just this minute!

**Comment by bsergean** [comment]
I was trying to use the unstable 4.x version of celery. I've upgraded to that one + amp 2.1.1 and it's running smoothly now. Thanks for the fix.

**Comment by cactus** [comment]
This issue appears to be back in amqp==2.1.2 w/python-2.7.5.
Reverting to amqp==2.1.1 seems to fix it.

**Comment by ask** [comment]
@cactus Thanks, a patch was submitted that changed it back to using unicode again by mistake, so now I have released amqp 2.1.3 which fixes the problem, again... :tada:

**Comment by 1ronmat** [comment]
Hello @ask !

Thanks to have solved my issue.
There is the same problem on amqp==2.1.4, just to say.
I reverted amqp to  amqp==1.2.3 and it works fine.
Thanks dude.

**Comment by imoore76** [comment]
Confirmed this is back in 2.1.4. Can we get this fixed again, please?

**Comment by thedrow** [comment]
and what about 2.2?
