### ISSUE TITLE
Unrecoverable error: TypeError("'NoneType' object is not callable",)

### ISSUE THREAD

**Issue by johnmilimo** [celery/py-amqp#113]
I am using Celery 4 and it doesn't work fine for me. I tried using librabbitmq AMQP client but the workers couldn't consume items from the queues. I then switched to pyamqp and the workers started consuming the items. The problem I have is that when I stop the workers and push items to queue, then start the workers, I get an error.

![x1](https://cloud.githubusercontent.com/assets/2853404/20305169/4018caae-ab45-11e6-9478-81d4097314cc.png)

![x2](https://cloud.githubusercontent.com/assets/2853404/20305186/5c4ae31a-ab45-11e6-939b-a130742fdcad.png)

The above error gets thrown if items are pushed to queue before running workers.

If workers are run before pushing tasks to queue, all works fine.

**Comment by ask** [comment]
librabbitmq doesn't work with Celery 4, and it's been falling behind on features for some time so pyamqp is a better choice.

Are you sending tasks using librabbitmq or pyamqp?

**Comment by phretor** [comment]
@ask I'm getting the exact same problem here. Same settings, same behavior.

**Comment by stevelittlefish** [comment]
I'm having the same issue.  If I start my web app without the celery workers running, and then create a couple of tasks, then start the celery worker, I see the exact same thing.  If I repeatedly restart the celery worker, I get this message a couple of times (more or less once per task), and then eventually it starts and processes all of my tasks.

Is there a fix for this?

**Comment by ask** [comment]
The same issue about _quick_put being empty has been reported to the Celery issue tracker, but I have yet to be able to reproduce it.

It would really help if someone had an minimal example project, able to reproduce the problem.

**Comment by chehsunliu** [comment]
https://github.com/chehsunliu/mycelerysample
Here is my simple sample project. I got the same error. The details are written in `README.md`.

**Comment by chehsunliu** [comment]
This issue is related to celery/celery#3620 and celery/celery#3539.

**Comment by njordr** [comment]
Hello.

I'm having the same issue, resolved installing py-amqp (as suggested by @ask )

**Comment by jdotjdot** [comment]
We use pyamqp and are still having this issue.

**Comment by GermanoGuerrini** [comment]
This should have been solved by a merge in https://github.com/celery/celery/pull/3752.
So far, no official release.

**Comment by radiantone** [comment]
Any workaround? I'm stuck

**Comment by nicolastobo** [comment]
stuck too. Any news ?

**Comment by navyad** [comment]
facing same issue with Celery 4.0 and amqp==2.1.4

**Comment by navyad** [comment]
i have resolved the issue with installing librabbitmq==1.6.1 

https://github.com/celery/kombu/issues/189

**Comment by navyad** [comment]
workaround i found is run celery worker with Q option specifying queues.

**Comment by smkher** [comment]
@navyad Running celery worker using Q option, still the same issue. Had to purge the queues and rerun the worker, then it works. Any got a fix yet? Stuck

**Comment by brownerg** [comment]
+1

**Comment by auvipy** [comment]
should have been fixed
