### ISSUE TITLE
Cannot import amqp with Python-2.7.6 (TypeError: Struct() argument 1 must be string, not unicode)

### ISSUE THREAD

**Issue by bendemboski** [celery/py-amqp#125]
ab395a0a19a52afaec3047e43a7b52b9b31d8313 re-fixed #107 but missed by one version. As you can see [here](http://python-future.org/stdlib_incompatibilities.html#struct-pack) or in the [2.7.7 changelog](https://hg.python.org/cpython/raw-file/f89216059edf/Misc/NEWS), the fix for issue 19099, which is what switched to requiring strings, wasn't introduced until 2.7.7.

So ab395a0a19a52afaec3047e43a7b52b9b31d8313 fixed the issue for all python versions except 2.7.6. [This line](https://github.com/celery/py-amqp/blob/4c382e0feb88a45a779100c970ecc65b91c03dae/amqp/platform.py#L45) just needs to be changed to

```python
if sys.version_info < (2, 7, 7):
```

**Comment by JonSchuff** [comment]
We ran into this issue as well for one of our services - created #134 based on @bendemboski's fix
