### ISSUE TITLE
2.2.0 issue in connection.py where it split mechanisms

### ISSUE THREAD

**Issue by naoko** [celery/py-amqp#156]
This issue only occurs in version `2.2.0` and `2.1.4` is good.

The issue occurred in amqp/connection.py
line# 344 
`self.mechanisms = mechanisms.split(b' ')`

where `mechanisms` is str but trying to split with byte string/
updating to `mechanisms.encode('utf-8').split(b' ')` temporarily fixed the connection problem.

**Comment by crohling** [comment]
Witnessed in python version 3.5

**Comment by crohling** [comment]
Actually, it seems this ticket duplicates: https://github.com/celery/py-amqp/issues/155
