### ISSUE TITLE
"expected a bytes-like object, str found" in self.mechanisms

### ISSUE THREAD

**Issue by jeffersonheard** [celery/py-amqp#160]
I get a [https://gist.github.com/jeffersonheard/2823d6c332f6db2750715c98fbba92db](stacktrace) when starting celery "flower" and only that, and the problem is: 

```
"/Users/jheard/Environments/flask_api/lib/python3.6/site-packages/amqp/connection.py", line 380, in _on_start
        b", ".join(self.mechanisms).decode()))
    TypeError: sequence item 0: expected a bytes-like object, str found
```

I was able to correct the problem by changing line 347 to:

```python
self.mechanisms = [bytes(x, 'utf-8') for x in (mechanisms.split(b' ') if isinstance(mechanisms, bytes) else mechanisms.split(' '))]
```

but I'm not sure this was the "root cause", and i don't know enough about amqplib to know whether my change is a valid one or just *happens* to fix the problem while introducing another that i'm not yet running into.

**Comment by georgepsarakis** [comment]
Have you tried with the current version? This seems fixed in this [commit](https://github.com/celery/py-amqp/commit/3782875cc5a671ed83acc2ebb0b9b7184549d123).

**Comment by georgepsarakis** [comment]
`v2.2.1` should contain the fix.

**Comment by thedrow** [comment]
It does.
