### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by FatalEnigma** [celery/py-amqp#161]
Hi,

Thank you for developing such an awesome project. I am looking to use celery with a project I am currently developing but have a query about this particular dependency.

I notice that last year the library was switched from LGPL to BSD but I noticed LGPL headers among some of the source files, are these no longer applicable? If so, why have they not been removed?

Thanks

**Comment by thedrow** [comment]
It is likely that @ask just missed those headers.
A pull request fixing this issue is welcome :)

**Comment by FatalEnigma** [comment]
Here you are :)
https://github.com/celery/py-amqp/pull/163

**Comment by thedrow** [comment]
This is now fixed :) Thanks!
