### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by gujun4990** [celery/py-amqp#171]
I am using amqp 2.1.4 verison and it doesn't work fine for me. The error appear on my openstack environment,
when amqp verison is 2.1.4, kombu verison is 3.0.32 and oslo_messaging version is 4.5.0.

The step is below:
1. I connect RabbitMQ server is Ok using amqp 2.1.4
2. Then, RabbitMQ server is down and amqp can't connect RabbitMQ server. The connection error wil be raised to kombu.
3. kombu will try to reconnect and amqp will create new channel. so amqp send open sig to RabbitMQ server, but it's failed and raise exception to oslo_messaging.
4. When oslo_messaging try to reconnect and amqp re-create new channel, the 'NoneType' error will occur.

The cause of this problem is that the step 3 don't clear the connection resource.
Bacause when executing the step 4, amqp mistakenly think it has connected the RabbitMQ server successfully.
From the code, the self.connected of Connection class is not None and the self.frame_writer of Connection class is None.
So the 'NoneType' error occur.

The code is blow:
amqp/connection:Connection

    def connect(self, callback=None):
        # Let the transport.py module setup the actual
        # socket connection to the broker.
        #
        if self.connected:
            return callback() if callback else None
        self.transport = self.Transport(
            self.host, self.connect_timeout, self.ssl,
            self.read_timeout, self.write_timeout,
            socket_settings=self.socket_settings,
        )
        self.transport.connect()
        self.on_inbound_frame = self.frame_handler_cls(
            self, self.on_inbound_method)
        self.frame_writer = self.frame_writer_cls(self, self.transport)

        while not self._handshake_complete:
            self.drain_events(timeout=self.connect_timeout)

So I prepare catch the exception on the create channel function at the step 3 and clear the connection resource.

The original code is below:
amqp/connection:Connection

    def channel(self, channel_id=None, callback=None):
        """Create new channel.

        Fetch a Channel object identified by the numeric channel_id, or
        create that object if it doesn't already exist.
        """
        if self.channels is not None:
            try:
                return self.channels[channel_id]
            except KeyError:
                channel = self.Channel(self, channel_id, on_open=callback)
                channel.open()
                return channel
        raise RecoverableConnectionError('Connection already closed.')

The modified code is below:
amqp/connection:Connection

    def channel(self, channel_id=None, callback=None):
        """Create new channel.

        Fetch a Channel object identified by the numeric channel_id, or
        create that object if it doesn't already exist.
        """
        if self.channels is not None:
            try:
                return self.channels[channel_id]
            except KeyError:
                channel = self.Channel(self, channel_id, on_open=callback)
                try:
                    channel.open()
                except Exception as exc:
                    self.collect()
                    raise
                return channel
        raise RecoverableConnectionError('Connection already closed.')
		
I wish someone can help me to review the code. Thank you!

**Comment by thedrow** [comment]
This is already fixed in later versions of kombu/amqp. Please upgrade.
