### ISSUE TITLE
Windows 7 x64 issue with TCP_KEEPCNT

### ISSUE THREAD

**Issue by MShekow** [celery/py-amqp#180]
Hi,

After having issues with celery 4.1 (worker couldn't connect to host, WinError 10042), I was able to nail down the issue:
In transport.py, 
```
TCP_OPTS = {
    getattr(socket, opt) for opt in KNOWN_TCP_OPTS if hasattr(socket, opt)
}
```
is populated just fine. But then in `_get_tcp_socket_defaults()` the call `sock.getsockopt(SOL_TCP, opt) for opt in TCP_OPTS` fails (with `opt == getattr(socket, 'TCP_KEEPCNT'`)

Best regards!

**Comment by darkdreamingdan** [comment]
Have you tried on amqp master? This might be resolved.

**Comment by thedrow** [comment]
This does look like it is resolved in the latest version or earlier.
