### ISSUE TITLE
Is there any backward-incompatible changes between 2.2.2 and 2.3 ?

### ISSUE THREAD

**Issue by hsiaoyi0504** [celery/py-amqp#191]
Originally, one of my project installed py-amqp 2.2.2, because celery is its requirements.
However, it seems to me that the Travis CI of my application fails today due the version update (2.2.2 -> 2.3.0). https://travis-ci.org/NAL-i5K/genomics-workspace/builds/384417734

Is there any backward-incompatible changes between 2.2.2 and 2.3.0 ? I had taken a look the change log (https://amqp.readthedocs.io/en/master/changelog.html), but I didn't find related information there (maybe just I am not familiar enough with py-amqp).

**Comment by juannyG** [comment]
Are you running this with python2.7?

**Comment by rnd0101** [comment]
Confirmed. One example where is failed:
```

    def str_to_bytes(s):                # noqa
        """Convert str to bytes."""
        if isinstance(s, string_t):
>           return s.encode('utf-8')
E           UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 3: ordinal not in range(128)
```

**Comment by hsiaoyi0504** [comment]
@juannyG Yes, my project is written in Python 2.7.

**Comment by quantoid** [comment]
Same fault for me; pip upgraded 2.2.2 to 2.3.0 and now `celery.control.inspect().stats()` raises a `UnicodeDecodeError`. Locking amqp to 2.2.2 for now.

**Comment by thedrow** [comment]
We're aware of the problem and working on a fix.

**Comment by Fokko** [comment]
We're experiencing the same issue at Apache Airflow

**Comment by hsiaoyi0504** [comment]
The issue is fixed in https://github.com/celery/py-amqp/releases/tag/v2.3.1.

**Comment by hsiaoyi0504** [comment]
I think I need to re-open this issue.
Although linux instance works, my build fails for MacOS.
https://travis-ci.org/NAL-i5K/genomics-workspace/builds/384782933

The build freeze at certain point.

**Comment by hsiaoyi0504** [comment]
Or should I update the celery version ?

**Comment by thedrow** [comment]
You should be using 4.1.1 or 4.2.0rc4.

**Comment by hsiaoyi0504** [comment]
@thedrow Actually, I am using 4.1.1, but builds on macs doesn’t work. It just freezes. I haven’t found the reason, but it seems to me it’s due to the update of Amal.

**Comment by anapaulagomes** [comment]
I'm having the same issue with MacOS. Celery 4.1.1 and OS HighSierra 10.13.4.

**Comment by thedrow** [comment]
I released amqp 2.3.1. I hope it helps.

**Comment by hsiaoyi0504** [comment]
@thedrow Sorry ... I have already updated to amqp 2.3.1, but it only fixed linux build, but mac builds fail . That's why I re-opened this issue.

**Comment by thedrow** [comment]
Yes. I just merged a fix for amqp on MacOS.
I'll try to find the time to release it today.

**Comment by thedrow** [comment]
Released.
