### ISSUE TITLE
channel.queue_declare raises TypeError

### ISSUE THREAD

**Issue by matusvalo** [celery/py-amqp#232]
PR #208 Introduces calls callbacks of wait with new parameter (`method`). This new parameter is returned via `wait()` method which breaks some code which does not expect this new parameter to be returned by `wait()` method.

Example broken script:

```python
import amqp
conn = amqp.Connection()
conn.connect()
ch = conn.channel()
ch.queue_declare('foo')
```
This script crash with exception:
```
TypeError: __new__() takes 4 positional arguments but 5 were given
```
The easy hot fix is as follows in `AbstractChannel::wait`
```python
            if p.value:
                args, kwargs = p.value
                args = args[1:]   # don`t return method parameter
                return args if returns_tuple else (args and args[0])
```

**Comment by pquentin** [comment]
With the 2.4 release, Channel.basic_consume now returns a tuple (consumer_tag,) instead of only the consumer_tag string, and sending that tuple to basic_cancel fails. Is this an expected change, or something that could be fixed in a future release?
