### ISSUE TITLE
Build broken for 2.4.0

### ISSUE THREAD

**Issue by thedrow** [celery/py-amqp#237]
Seems like the integration tests are flaky.
@matusvalo since you contributed them do you mind taking a look?
See https://travis-ci.org/celery/py-amqp/jobs/479015397

**Comment by matusvalo** [comment]
Fixed in #236. But afrer bumping version of pypy the tests are failing but in place not connected to integration tests. Moreover, in PR run of CI the failed test passed.

**Comment by matusvalo** [comment]
Hm strange, I have manually triggered builds 3 times in travis and all the time all tests passed. Not sure why this particular build failed. Now everything is green.
