### ISSUE TITLE
basic_publish returns a tuple instead of a `consumer_tag`

### ISSUE THREAD

**Issue by xordoquy** [celery/py-amqp#239]
Hi,

Since 2.4, I notice the call to `basic_consume` without `consumer_tag` nor `nowait` now returns a tuple with a `consumer_tag` instead of the `consumer_tag` itself as was the case in the previous release.
It is not clear to me whether it's intended or not.

**Comment by xordoquy** [comment]
I saw that PR but fail to understand whether or not the change in the returned value was intended.
@matusvalo, any idea about ?

**Comment by matusvalo** [comment]
Done. I have also added issue for improving API of `basic_consume()` - #241.

**Comment by pquentin** [comment]
@thedrow a bug fix release would be nice! We currently need this workaround in our code:

```
if isinstance(consumer_tag, tuple):
    consumer_tag = self.consumer_tag[0]
```

Thank you for your work on py-amqp!
