### ISSUE TITLE
Missing TCP_MAXSEG TCP option on IBM i platform (transport.py in AMQP)

### ISSUE THREAD

**Issue by tracym1964** [celery/py-amqp#273]
I am using amqp 2.4.2 and kombu 4.5.0 Python packages on an IBM i system (PASE environment) where the IBM i OS is 7.3.  My Python version is 3.6.8 using GCC for aix6 6.3.0.  I am receiving an invalid TCP socket option on line 215 in transport.py within amqp package.  This line is within the _get_tcp_socket_defaults() method.  The TCP option is TCP_MAXSEG which apparently does not exist on the IBM i implementation of the TCP/IP stack.  I removed TCP_MAXSEG from the list of KNOWN_TCP_OPTS defined in platform.py file in the same amqp package which provided a work-around for me.  Can you use a try/except block to catch the situation when this option is not available similar to what is already being done for the TCP_USER_TIMEOUT option?  I see that this option is available in Linux, bu
![transport_py_problem](https://user-images.githubusercontent.com/24413318/55506155-5ebb9180-561a-11e9-977d-d890b5398dd1.png)
t not on all platforms.  (My test program works fine without modification when testing from Fedora 28).

**Comment by thedrow** [comment]
Please update the following file with the socket options available for your platform:
https://github.com/celery/py-amqp/blob/master/amqp/platform.py#L41

**Comment by tracym1964** [comment]
Thank you very much for your reply!

I added the following lines to 'platform.py', and my program is working. 
  I have attached the entire file with the modification.

# aix does not allow to set the TCP_MAXSEG socket option
elif sys.platform.startswith('aix'):
     KNOWN_TCP_OPTS.remove('TCP_MAXSEG')
     KNOWN_TCP_OPTS.remove('TCP_USER_TIMEOUT')

Tracy Martin
tracym@angularisllc.com

**Comment by thedrow** [comment]
Would you like to issue a PR or should I apply the patch?

**Comment by tracym1964** [comment]
Since I haven't issued a PR before, could you apply the patch?

Thank you!

Tracy Martin

**Comment by thedrow** [comment]
Sure!
