### ISSUE TITLE
is librabbitmq recommended?

### ISSUE THREAD

**Issue by davidszotten** [celery/py-amqp#274]
Hi,

The readme states
> [...] used by kombu as a pure python alternative when librabbitmq is not available.

However, librabbitmq has much less activity than py-amqp, and responses to several issues there seem to recommend this instead. 

Which is the recommended library to use? If py-amqp, does the readme need updating? 

Thanks for a great suite of tools!

D

**Comment by auvipy** [comment]
no not anymore
