### ISSUE TITLE
Infinite wait when using confirm_publish

### ISSUE THREAD

**Issue by maingoh** [celery/py-amqp#276]
I am trying to get a robust amqp client and with this code I get an infinite wait in the last publish.

```python
from kombu import Connection, Producer, Queue
from amqp.exceptions import NotFound
import uuid
import os

c = Connection(amqp_url, transport_options={'confirm_publish': True})
p = Producer(c)
q = Queue('my-queue-{}'.format(uuid.uuid4()), channel=c)
q.declare()
p.publish({'foo': 'bar'}, routing_key=str(uuid.uuid4()), retry=False)

q.delete()
try:
    q.get()
    raise Exception("This should raise a NotFound")
except NotFound:
    q.declare()

p.publish({'foo': 'bar'}, routing_key=str(uuid.uuid4()), retry=False)

```

It seems there is no timeout property here https://github.com/celery/py-amqp/blob/09cf92a643ed075d048856a56a2e730482401558/amqp/channel.py#L1789

- kombu 4.5.0 
- pyamqp 2.4.2 

Any idea of what happens ? Thank you !

**Comment by matusvalo** [comment]
The reason of it is because channel error occurred (`NotFound`). As long as I understand, channel in AMQP protocol should be closed after channel error and new one should be opened. Possible fix in this example is:
```python
from kombu import Connection, Producer, Queue
from amqp.exceptions import NotFound
import uuid
import os

c = Connection('t3dcpfdp01', transport_options={'confirm_publish': True})
p = Producer(c)
q = Queue('my-queue-{}'.format(uuid.uuid4()), channel=c)
q.declare()

p.publish({'foo': 'bar'}, routing_key=str(uuid.uuid4()), retry=False)

q.delete()
try:
    q.get()
    raise Exception("This should raise a NotFound")
except NotFound:
    q.declare()

p = Producer(c.channel())
p.publish({'foo': 'bar'}, routing_key=str(uuid.uuid4()), retry=False)
```

In my opinion this is not issue on pyamqp side. Maybe Kombu can be improved that it can automatically create new channel when Channel error occurs.

**Comment by thedrow** [comment]
But I do think a timeout is a good idea.
@matusvalo What do you think?

**Comment by thedrow** [comment]
@maingoh Check the PR. Let me know what you think.

**Comment by maingoh** [comment]
Thank you, I actually didn't know that channels couldn't be reused after errors. So if a channel error occurs on the connection `default_channel`, we have to recreate a `default_channel` and revive all created entities with default channel ? 
I guess it is better to have one entity/one channel then no ?

**Comment by thedrow** [comment]
I think that's the default behavior.
If you don't specify a channel it will be created for you.
