### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by moggers87** [celery/py-amqp#278]
See https://travis-ci.org/celery/py-amqp/builds

It appears to have been since 3f6818708987a69ca32a209ad50e205943ecaae5, though I don't see how that would break anything; alpha releases aren't normally installed, so nothing really changed

**Comment by thedrow** [comment]
I'll check it out.

**Comment by thedrow** [comment]
Thanks for the heads up.
I would have never noticed in a timely manner.
