### ISSUE TITLE
SNI is broken on python 2.7

### ISSUE THREAD

**Issue by dhananjaysathe** [celery/py-amqp#282]
Pull request https://github.com/celery/py-amqp/pull/215 breaks on python 2.7 it works against ssl but breaks SNI as the wrap method quick exits for some reason

**Comment by matusvalo** [comment]
@dhananjaysathe the this issue connected to #283 ? Can you provide some minimal failing code snippet?

**Comment by dhananjaysathe** [comment]
There wont be any failing code in the traditional sense. You would need to run it against a rmq server behind a tcp proxy (like HAProxy) using SNI to route traffic. It wont send the header and will fail . In the pr i have detailed the code path that causes it to fail. More like a integration test of some sort i dunno how you could include that in your current setup, but would be interesting to know

**Comment by thedrow** [comment]
There's #270 which specifies that we need integration tests for our SSL transport.
I tried setting it up myself but it didn't work and the client did not connect.
I didn't have a clue on why is that.
@dhananjaysathe Care to give it a shot?

**Comment by matusvalo** [comment]
python 2.7 is not supported - closing the issue.
