### ISSUE TITLE
amqp didn't send whole message to rabbitmq

### ISSUE THREAD

**Issue by dingzhengkai** [celery/py-amqp#284]
Hi, anyone can help to figure out what's wrong to my situation? And how to send long msg to rabbitmq?

I use the following code to publish the msg, about 1500 char, but rabbitmq didn't receive the whole msg, when i upgrade amqp to 2.5.0, the problem was solved. 

My environment:
```
Python 3.6.7 :: Anaconda custom (64-bit)
OS "Ubuntu 18.04.3 LTS"
amqp==2.2.1
```
My code:
```
channel.basic_publish(amqp.Message(body=msg, content_encoding='utf-8',
                 message_id="o0o0o0",
                 expiration='15000',
                 app_id='java',
                 delivery_mode=1,
                 application_headers={
                     'actionid': actionid,
                     'sessionid': actionid,
                     'messagetype': 'xxx'
                 }
                 ),
    exchange='ex_service_router', routing_key='xx')
```

**Comment by dingzhengkai** [comment]
I had enabled the rabbitmq tracing plugin to see if the whole msg was arrived to the queue correctly, the answer was not.

**Comment by thedrow** [comment]
If this was fixed in a later version of py-amqp, please upgrade.

**Comment by dingzhengkai** [comment]
@thedrow , thanks for your reply. Sorry that i'm a newbie in python and amqp, i just want to learn if there are  any special params   in py-amqp need be used when sending long msg to rabbitmq

**Comment by thedrow** [comment]
No there aren't.
