### ISSUE TITLE
The consumption log of events is about 2 minutes later than the time of sending the log, but there is no queue backlog in the monitoring of rabbitmq, so we want to consume the message as soon as possible.

### ISSUE THREAD

**Issue by Ludasheng** [celery/py-amqp#290]
Record a survey of rabbitmq consumption problems:

Problem: The consumption log of events is about 2 minutes behind the time of sending the log, but there is no queue backlog for monitoring rabbitmq

Queuing: The queue is not backlogged, but the consumption is delayed. It is suspected that the consumer has taken the data to memory, so there is no backlog in the queue, but the time spent on consuming one is 2-3 seconds, so the order consumption in memory is delayed. The performance is the time spent on the log.

Experiments: First stop queuing consumers, then producers produce 30 data, monitoring can see that the number of events to be consumed is 30, then start consumers, monitoring data instantly is 0, but the consumer log output lasts about 2 minutes. This phenomenon coincides with the conjecture that both consumers take data into memory and queue it in memory for processing.

Processing: Set the queue consumer to need manual ACK mode, and set the consumer's receiving window to one, which receives one, consumes one, responds one and then takes the next, so that queue monitoring can display the status of queue backlog in real time (no_ack=False, basic_qos(), basic_ack()).

Additional Note: In fact, tasks that can be processed asynchronously can generally tolerate a certain delay or do not require real-time, but the real-time nature of the business needs to be processed when the problem arises and each processing is time-consuming, so this problem will arise. Previous business does not require the event to enter immediately after the event. Consumption, so there is not much concern about whether consumption time is consistent with the backlog of queue monitoring.

To be confirmed: According to the previous phenomenon, the consumption delay is about 3 minutes, and each consumer has 2-3 seconds, that is, the number of queues in memory is about 60, while in the basic class constants of rabbitmq, there are the following configurations: so guess if the consumer does not need manual confirmation, and does not set the receiving window, silently. The number of windows is 60, but in view of the limited capacity, it can not be 100% confirmed, and we still look forward to God's advice.

class Basic:
    """AMQ Basic class."""
    CLASS_ID = 60
    **Qos = (60, 10)**
    QosOk = (60, 11)
    Consume = (60, 20)
    ConsumeOK = (60, 21)

**Comment by thedrow** [comment]
Why did you close the issue?
Is this a mistake?
