### ISSUE TITLE
Tagged 2.5.1 release versioned as 2.5.0

### ISSUE THREAD

**Issue by aetimmes** [celery/py-amqp#298]
https://github.com/celery/py-amqp/blob/84481db19bec9e82e4fdf19d49216c8bf3e7100d/amqp/__init__.py#L9 <-- should list 2.5.1 and not 2.5.0.

This causes 2.5.1 to install in the location of 2.5.0 when setup.py is run against it, which breaks dependencies for celery etc.

**Comment by auvipy** [comment]
which version are you trying? https://github.com/celery/py-amqp/blob/master/amqp/__init__.py

**Comment by aetimmes** [comment]
I am trying the version tagged as 2.5.1.

If you download the 2.5.1 tagged release version from the releases tab
here: https://github.com/celery/py-amqp/releases

and expand the tar and read amqp/__init__.py, the __version__ variable
inside is specified as 2.5.0.

**Comment by auvipy** [comment]
try the latest release

**Comment by aetimmes** [comment]
Hmm - last time I tried, I was using kombu 4.6.5 so amqp 2.5.1 was the only
option. I seem to have missed the kombu 4.6.6 release allowing for the use
of 2.5.2.

I'll try to rebuild using 2.5.2 - it should likely work. If you don't think
the version variable is worth updating retroactively, feel free to close
this issue.
