### ISSUE TITLE
ssl.wrap_socket() is deprecated

### ISSUE THREAD

**Issue by matusvalo** [celery/py-amqp#303]
`ssl.wrap_socket()` from https://github.com/celery/py-amqp/blob/78ce51d5b4274fb2005b26f9d3e0bb4775b4d041/amqp/transport.py#L353 is deprecated from python 3.7 (see [1]). Based on documentation `SSLContext.wrap_socket()` should be used instead.

[1] https://docs.python.org/3/library/ssl.html#ssl.wrap_socket

**Comment by elijose55** [comment]
Can I work on this issue?
