### ISSUE TITLE
amqp.Message(timestamp:datetime)?

### ISSUE THREAD

**Issue by icemac** [celery/py-amqp#307]
The documentation for the `timestamp` parameter of `amqp.Message`says it has to be of the type ` datetime.datetime`, see https://github.com/celery/py-amqp/blob/78ce51d5b4274fb2005b26f9d3e0bb4775b4d041/amqp/basic_message.py#L58-L59

When actually using a `datetime` here I get `error: cannot convert argument to integer` in https://github.com/celery/py-amqp/blob/78ce51d5b4274fb2005b26f9d3e0bb4775b4d041/amqp/serialization.py#L297

It seems that `dumps` expects `timestamp` to be go type `long long`.
(`amqplib` was converting `timestamp` via `time.mktime(val.timetuple())` to an int value.

Is my usage resp. understanding wrong or the documentation?

**Comment by matusvalo** [comment]
@icemac I confirm your bug.
