### ISSUE TITLE
read/write timeouts?

### ISSUE THREAD

**Issue by theflow** [celery/py-amqp#32]
(not sure if this belongs to kombu or here)

I'm trying to understand how kombu/amqplib is supposed to behave when the TCP connection goes away silently and why there is no mechanism to define read/write timeouts (similar to the ones in libmemcached, for example http://docs.libmemcached.org/memcached_behavior.html#MEMCACHED_BEHAVIOR_SND_TIMEOUT).

To simulate this I'm running celery with RabbitMQ, start a celery worker and a task submitter and then SIGSTOP the RabbitMQ server. The celery consumer never notices anything is wrong, the task submitter submits tasks until the TCP buffer is full (which takes quite a while) and then fails with an error, all the published tasks are lost.

How can I detect this earlier?

**Comment by auvipy** [comment]
https://github.com/celery/py-amqp/pull/42
