### ISSUE TITLE
Framing errors on windows when using timeout due to BlockingIOError not handled right

### ISSUE THREAD

**Issue by timburke** [celery/py-amqp#320]
### High Level Summary

I've been tracking down an issue where using both the latest released stable and current `master` versions of `py-amqp` sometimes resulted in framing errors or py-amqp losing synchronization with the stream of frames coming from rabbitmq, causing it to hang because it misread data inside a message as the length of the next message.  

The bottom line turned out to be that there's an unhandled edge case inside `_AbstractTransport.read_frame` when used with a timeout on the read.  It checks for certain timeout errors in order to requeue partially read data but misses some exceptions that can be raised (at least on Windows).

I found that **sometimes** on Windows 10 at least, the `recv` call on a socket that is set with a timeout can raise `BlockingIOError`.  This does not cause data requeuing inside of `read_frame` which means that the next time someone calls `drain_events()` there will be 1 frame header (typically) chomped and the next frame will not be synchronized.

### Details

From the `read_frame` code:

```python
    def read_frame(self, unpack=unpack):
        read = self._read
        read_frame_buffer = EMPTY_BUFFER
        try:
            frame_header = read(7, True)
            read_frame_buffer += frame_header
            frame_type, channel, size = unpack('>BHI', frame_header)
            # >I is an unsigned int, but the argument to sock.recv is signed,
            # so we know the size can be at most 2 * SIGNED_INT_MAX
            if size > SIGNED_INT_MAX:
                part1 = read(SIGNED_INT_MAX)
                part2 = read(size - SIGNED_INT_MAX)
                payload = b''.join([part1, part2])
            else:
                payload = read(size)
            read_frame_buffer += payload
            ch = ord(read(1))
        except socket.timeout:
            self._read_buffer = read_frame_buffer + self._read_buffer
            raise
        except (OSError, IOError, SSLError, socket.error) as exc:  # <---- HERE IS THE PROBLEM
            # Don't disconnect for ssl read time outs
            # http://bugs.python.org/issue10272

            if isinstance(exc, SSLError) and 'timed out' in str(exc):  # <--- SECOND LATENT PROBLEM
                raise socket.timeout()
            if get_errno(exc) not in _UNAVAIL:
                self.connected = False
            raise
        if ch == 206:  # '\xce'
            return frame_type, channel, payload
        else:
            raise UnexpectedFrame(
                'Received {0:#04x} while expecting 0xce'.format(ch))
```

Note how if a `socket.timeout` happens, there is an explicit re-queuing of the partially read data into `self._read_buffer`.  However when an `OSError` happens, this does not occur.  One of the potential `OSError` options is `BlockingIOError`, which appears to be raised in some circumstances on Windows at least.  See [BlockingIOError](https://docs.python.org/3/library/exceptions.html#BlockingIOError).  

From the python docs though, it looks like `BlockingIOError` would be raised anytime `recv` returned `EAGAIN`, `EALREADY`, `EWOULDBLOCK` and `EINPROGRESS`.  So, this issue could potentially also affect linux and other OSes that can return `EWOULDBLOCK` from `recv` call.

I have a bunch of detailed logs where I added in extra logging statements to verify that this is what was happening but I want to ask the question of if there's a reason for `BlockingIOError` to be handled differently or if I should just make a PR with a fix handling that case similar to how `socket.timeout` is handled.

Note that there also seems to be the same bug when `SSLError` with `timed out` in the `str(exc)` happens that will also cause a loss of synchronization.

The actual flow of what happens is:

1. `frame_header` is read (7 bytes) and added to `read_frame_buffer` with no error.
2. The next `read(size)` times out with `BlockingIOError`. 
3. Since the error is not a `socket.timeout`, the `read_frame_buffer` is not added back to `self._read_buffer` so the 7 bytes are dropped and subsequent reads will be corrupted.
4. However, it looks like `having_timeout` does translate `BlockingIOError` back into a `socket.timeout` so calling code does not know the difference and the error silently causes data corruption until the connection finally dies due to an eventual framing error.

Looking at the `having_timeout` code, it looks like if `EWOULDBLOCK` is raised by a `recv` then this will be translated to `BlockingIOError` and then translated back to `socket.timeout` `having_timeout` but bypassing the logic to requeue the partially read data.

I'll open a PR with a fix.

**Comment by timburke** [comment]
Some additional clarify/corrections here.  It looks like the error **is not**  technically a subclass of `BlockingIOError` but rather a `socket.error`.  

I modified `read_frame to add the following clause into the except handler:

```python
except (OSError, IOError, SSLError, socket.error) as exc:
            # Don't disconnect for ssl read time outs
            # http://bugs.python.org/issue10272

            if isinstance(exc, socket.error):
                LOG.debug("We got a socket error %s: errno = %s", exc, get_errno(exc))

            LOG.debug("NOT UPDATING READ BUFFER BECAUSE OF ERRROR (dropping %d)", len(read_frame_buffer), exc_info=True)
```

This generated the following log messages when I reproduced the error:

```
20-05-09 21:29:56.425 DEB amqp.transport We got a socket error [WinError 10035] A non-blocking socket operation could not be completed immediately: errno = 10035
20-05-09 21:29:56.425 DEB amqp.transport NOT UPDATING READ BUFFER BECAUSE OF ERRROR (dropping 7)
Traceback (most recent call last):
  File "c:\arch\edge\py-amqp\amqp\transport.py", line 265, in read_frame
    payload = read(size)
  File "c:\arch\edge\py-amqp\amqp\transport.py", line 454, in _read
    s = recv(n - len(rbuf))
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately
```

It looks like on Windows, you can get a `socket.error` with `errno` set to `10035`.  When `exc_info=True` is passed to `logging`, it prints as `BlockingIOError` but it's a subclass of `socket.error`.

So, it seems like this is a windows only error case, which makes sense because there is logic inside of the python `socket` module that should have kept retrying the read if an `EWOULDBLOCK` error was set:
https://github.com/python/cpython/blob/master/Modules/socketmodule.c#L965

For reference, this is Python 3.8.0 on Windows 10.

**Comment by thedrow** [comment]
PRs welcome :)

**Comment by timburke** [comment]
@thedrow Understood :)  Thank you for taking the time to review the issue and I will open a PR to fix it.

**Comment by auvipy** [comment]
thanks for your detailed report! looking forward to the PR!

**Comment by timburke** [comment]
PR on the way.

Just adding some additional notes for reference.  Turns out that on Windows, CPython defines `errno.EWOULDBLOCK = 10035`.  

```
(env) PS > python                                                                                                                                                                                       Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import errno
>>> errno.EWOULDBLOCK
10035
>>> quit()
```

This is why `having_timeout()` turns this error back into a `socket.timeout()` error.  The place in CPython that does this platform-specific definition of `EWOULDBLOCK` is here:
https://github.com/python/cpython/blob/3466922320d54a922cfe6d6d44e89e1cea4023ef/Modules/errnomodule.c#L264

**Comment by timburke** [comment]
PR open here:
https://github.com/celery/py-amqp/pull/321

**Comment by auvipy** [comment]
thanks!
