### ISSUE TITLE
Unicode error if "long string" type header property is not UTF-8 encoded

### ISSUE THREAD

**Issue by timburke** [celery/py-amqp#323]
I've run into what I believe is a bug in how py-amqp deserializes message headers.  In particular, `py-amqp` assumes that `long string` entries in a header `field table` will always be valid utf-8 whereas this is not required by the standard.

The problem is reliably reproduced when `py-amqp` receives messages that were originally published to rabbitmq over AMQP 1.0.  RabbitMQ stores the orginal AMQP 1.0 headers in an `x-amqp-1.0-properties` with type `long string` including the amqp 1.0 framing bytes, which make the string not valid utf-8.

## Detailed Error Description

- When `py-amqp` encounters a header of type `field_table`, it parses out all of the key,value pairs in the field table.
    ```python
    elif ftype == 'F':
        tlen, = unpack_from('>I', buf, offset)
        offset += 4
        limit = offset + tlen
        val = {}
        while offset < limit:
            keylen, = unpack_from('>B', buf, offset)
            offset += 1
            key = pstr_t(buf[offset:offset + keylen])
            offset += keylen
            val[key], offset = _read_item(buf, offset)
    ```

     Reference: https://github.com/celery/py-amqp/blob/master/amqp/serialization.py#L117

- This code passes the value to `_read_item` to deserialize.  `_read_item` again looks at the type of the value and deserializes it accordingly.  If the type is `S` (long string), then `_read_item` deserializes it using:
   ```python
    # 'S': long string
    if ftype == 'S':
        slen, = unpack_from('>I', buf, offset)
        offset += 4
        val = pstr_t(buf[offset:offset + slen])
        offset += slen
    ```

    Reference: https://github.com/celery/py-amqp/blob/master/amqp/serialization.py#L45

- `pstr_t` calls `bytes_to_str`, which deserializes by using:

   ```python
   if isinstance(s, bytes):
        return s.decode('utf-8', 'surrogatepass')
   ```

   Reference: https://github.com/celery/py-amqp/blob/5f034578c9a85d54f4b4cb9709a9afb5306b3c30/amqp/utils.py#L77

- If the value is not a valid UTF-8 string, then this fails and raises a `UnicodeDecodeError` and the connection is broken from then on (since `py-amqp` can never get past this message).

So, the issue is the `py-amqp` will fail if it receives a message that has a header property with a `long string` value that is not valid utf-8.  I checked in the AMQP 0.9.1 spec and it is allowed for `long string` types to contain arbitrary bytes.  See page 35 of the AMQP 0.9.1 spec [linked here](https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf) for reference.  The relevant section is:
![image](https://user-images.githubusercontent.com/2424759/83312479-436cf780-a1c7-11ea-8758-a394d1525f13.png)

**Bottom Line:** `py-amqp` assumes that a long-string value inside a `field table` will be valid `UTF-8` whereas that is only required for short strings and long strings are allowed to have arbitrary data.

### Impact

`py-amqp` generally fails when processing messages that were originally published via amqp 1.0 if there are any properties set in the original message (such as `message-id`) since the amqp 1.0 framing bytes will make the value not valid utf-8 even if it were originally a utf-8 string.

## Resolution

In order to maintain backwards compatibility with the current behavior that will turn properties into `str` objects, I propose catching the `UnicodeDecodeError` and returning bytes only if the header failed to decode as valid utf-8:

```python
   # inside _read_item()
   # 'S': long string
    if ftype == 'S':
        slen, = unpack_from('>I', buf, offset)
        offset += 4
        try:
            val = pstr_t(buf[offset:offset + slen])
        except UnicodeDecodeError:
            val = buf[offset:offset + slen]

        offset += slen
```

I'll open a PR with this fix but am open to amending if there's a better way to handle this.  This was the minimal fix I could come up with that wouldn't break any application that previously worked expecting that `long strings` would be turned into `str` automatically.

**Comment by auvipy** [comment]
thanks
