### ISSUE TITLE
Disable heartbeats log

### ISSUE THREAD

**Issue by Llandy3d** [celery/py-amqp#326]
On version 2.0.0 debug logging for heartbeats was added, it does not seem to be possible to disable them.
Is there something that can be done or is it a feature that could be added ?

**Comment by 4383** [comment]
Hello,

heartbeat logs are all to debug level [1] so have you try to simply ignore the debug level on your side?
I personnally think that these logs are properly implemented and useful in debug mode so if we introduce feature to disable them by using another way than simply ignore debug level could hide things during debug session.

[1] https://github.com/celery/py-amqp/commit/0416761daf88a8fdd60454b2515242be83d783c0

**Comment by Llandy3d** [comment]
Hi, 

the linked commit tells exactly my needs and it seems that I was using an older version where it was still using the amqp logger while I wanted to disable only the heartbeats, with that I solved my problem, Thank you

**Comment by 4383** [comment]
@Llandy3d you're welcome :)
