### ISSUE TITLE
'Server unexpectedly closed connection'

### ISSUE THREAD

**Issue by filiprosco** [celery/py-amqp#392]
Hello
Here is my setup:
- I am running Apache Active MQ docker container locally
- Trying to connect to it using this library, instantiating connection in a few different ways:
     -   with amqp.Connection(host='localhost:5672', userid='admin', password='admin', login_method='AMQPLAIN') as c:
     -   with amqp.Connection(host='localhost:5672') as c:

But regardless I am getting 
          **\transport.py", line 635, in _read
          raise OSError('Server unexpectedly closed connection')
      OSError: Server unexpectedly closed connection**

Is there anything I am missing in parameters/ MQ configuration ? I couldn't find anything online regarding this.
Any help much appreciated !
Thanks !

**Comment by auvipy** [comment]
share more detail please

**Comment by auvipy** [comment]
this package is for rabbitmq mainly

**Comment by filiprosco** [comment]
> share more detail please

What other details you are interested in ?

**Comment by filiprosco** [comment]
> this package is for rabbitmq mainly

So this library cant be used to communicate with Apache MQ ?

**Comment by filiprosco** [comment]
Rabbit MQ is using AMQP 0.9.1 vs Active MQ AMQP 1.0, so therefore this library is no good, please someone confirm

**Comment by auvipy** [comment]
not this can't, you should have read the docs properly
