### ISSUE TITLE
release a new version / adding support for Python 3.12/3.13

### ISSUE THREAD

**Issue by jugmac00** [celery/py-amqp#439]
it looks like that support for at least Python 3.12 is tested, but not yet released
see https://github.com/celery/py-amqp/blob/cc10bbe4aea41147356edf39859b349cb4e2de3a/.github/workflows/ci.yaml#L10

**Comment by Nusnus** [comment]
https://github.com/celery/py-amqp/releases/tag/v5.3.0 @jugmac00

**Comment by Nusnus** [comment]
@jugmac00 
> @Nusnus no release to pypi anymore?

I pushed to pypi _before_ I release the changelog/tag on GitHub normally, so if you see it here, you can already `pip install` it.
https://pypi.org/project/amqp/5.3.0/

![CleanShot 2024-11-12 at 21 33 15](https://github.com/user-attachments/assets/0d557c78-0a00-48a0-97d3-9c44a7814648)

**Comment by jugmac00** [comment]
Thank you!

**Comment by Nusnus** [comment]
Just released a patch version to fix the documentation build failure.
- Git: https://github.com/celery/py-amqp/releases/tag/v5.3.1
- PyPI: https://pypi.org/project/amqp/5.3.1/
- Docs: https://amqp.readthedocs.io/

@jugmac00 FYI
