### ISSUE TITLE
Setup.py PyPi licensing metadata and LICENSE file are not aligned

### ISSUE THREAD

**Issue by gwachob** [celery/py-amqp#82]
Hi folks-
   I'm tasked with going through the licensing on  dependencies on a project, and I've noticed that the licensing trove classifiers indicate both BSD and LGPL, but the LICENSE file only contains LGPL. Can this be clarified (either by removing the line from the setup.py or modifying/extending the LICENSE file)?

**Comment by ask** [comment]
Ooops, I think the license needs to stay LGPL unless we can get permission from Barry Pederson.

This is originally a fork of his amqplib project which is LGPL, though the code is almost entirely rewritten at this point.

**Comment by cwill747** [comment]
+1 on this - weird to me that everything I've seen in the celery project is not licensed LGPL but this is - would be nice to align to one license

**Comment by cwill747** [comment]
@barryp thoughts on BSD 3-clause-ing this code?

**Comment by barryp** [comment]
I don't have strong feelings about LGPL vs BSD, so if switching your fork helps you guys out I say go for it.

**Comment by ask** [comment]
@barryp Thank you so much for amqplib and other contributions, there wouldn't be a Celery without you!  I'm very happy we can unify the license :tada:

**Comment by barryp** [comment]
@ask You're very welcome!  I'm thrilled that it's being used in such a cool project.
